# -*- coding: utf-8 -*-
"""ads_CTR_Optimisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ryf0qTBcQ6A9LWPPwDdPIr536ubPqlaj
"""

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/MyDrive/colab"

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

df = pd.read_csv("/content/drive/MyDrive/colab/Ads_CTR_Optimisation.csv", sep =',', header = 'infer')

df

N = 10000
d = 10
ads_selected = []
no_of_selection = [0]*d
sum_of_rewards = [0]*d
total_reward = 0

for n in range(0,N):
  ad = 0
  max_upper_bound = 0
  for i in range(0,d):
    if(no_of_selection[i]>0):
      avg_reward = sum_of_rewards[i] / no_of_selection[i]
      delta_i = math.sqrt(3/2 * math.log(n+1)/no_of_selection[i])
      upper_bound = avg_reward + delta_i
    else:
      upper_bound = 1e400
    if upper_bound > max_upper_bound:
      max_upper_bound = upper_bound
      ad = i
  
  ads_selected.append(ad)
  no_of_selection[ad] += 1
  reward = df.values[n,ad]
  sum_of_rewards[ad] += reward
  total_reward += reward

plt.hist(ads_selected)

import math

N = 10000
d = 10
ads_selected = []
no_of_rewards_1 = [0]*d
no_of_rewards_0 = [0]*d
total_rewards = 0

import random
for n in range(0,N):
  max_random = 0
  for i in range(0,d):
    random_beta = random.betavariate(no_of_rewards_1[i] + 1, no_of_rewards_0[i] + 1)

    if random_beta > max_random:
      max_random = random_beta
      ad = i
  ads_selected.append(ad)
  reward = df.values[n,ad]


  if reward == 1:
    no_of_rewards_1[ad] = no_of_rewards_1[ad] + 1
  else:
    no_of_rewards_0[ad] = no_of_rewards_0[ad] + 1

    total_rewards += reward

plt.hist(ads_selected)

