# -*- coding: utf-8 -*-
"""covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_xkcneVJ-ZUS3AM80A9whzzt7KDTSkHg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/MyDrive/colab"

df = pd.read_csv('/content/drive/MyDrive/colab/country_wise_latest.csv' , sep =',',header = 'infer' )

df

df.head()

#a1 = df.loc[df.Active==0,:]
#a1.plot.scatter('Confirmed', 'Recovered');
columns = ["Deaths","Recovered"]
plt.plot(df.Deaths , color = 'red')
plt.plot(df.Recovered, color = 'black')
plt.xlabel("Deaths")
plt.ylabel("Recovered")
plt.show()

plt.plot(df.Confirmed, color = 'r', linewidth = '2')
plt.plot(df.Deaths , color = 'black', linewidth = '2')
plt.plot(df.Recovered, color = 'y' , linewidth = '2')
plt.plot(df.Active , color = 'magenta' , linewidth = '2')
plt.legend(['Confirmed','Deaths','Recovered','Active'])
plt.show()

data = pd.read_csv('/content/drive/MyDrive/colab/day_wise.csv' , sep =',',header = 'infer' )

data

data.columns

df.columns

data.describe()

df.describe()

data.isnull().sum()

df.isnull().sum()

