# -*- coding: utf-8 -*-
"""geopy and folium.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nN5o8lfg-m0L8R9PIED9H-KjAtYpBaf0
"""

pip install geopy

pip install folium

import pandas as pd
import folium
from geopy.distance import geodesic as GD

"""##### Task 1: Consider Names of two places from the user and find out the distance between them using Geopy library and Mark the location using folium. Now connect both two places on the map by line using Polyline method"""

from geopy.geocoders import Nominatim

a = input("Enter location1: ")
b = input("Enter location2: ")

geolocator  =  Nominatim(user_agent="my_request")
location1 = geolocator.geocode(a)
location2 = geolocator.geocode(b)
print(location1.address)
print((location1.latitude,location1.longitude))
la1 , lo1 = location1.latitude, location1.longitude;
A = (la1,lo1)
print(location2.address)
print((location2.latitude,location2.longitude))
la2 , lo2 = location2.latitude, location2.longitude;
B = (la2,lo2)
print("The distance between two places are: ", GD(A,B).km)

"""##### Task 2. Using “list-indian-states-and-capitals.csv” file get the name of Indian-state-capitals using Geopy find the latitude and longitude of the Indian-state-capitals and label the capital on the map using folium."""

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/My Drive/colab"

dataset = pd.read_csv("/content/drive/My Drive/colab/list-indian-states-and-capitals (1).csv", sep = ',', header = "infer")

dataset

from geopy.geocoders import Nominatim
capital = input("Enter the capital: ");
geolocator = Nominatim(user_agent = 'dataset')
location = geolocator.geocode(capital)
print(location.address)
print((location.latitude, location.longitude))
la , lo = location.latitude, location.longitude;

capital = folium.Map(zoom_start=2)
folium.Marker( location=[la, lo]).add_to(capital)
capital

"""##### Task 3. Using excel file related to COVID 19 data, find the latitude &amp; longitude of the states. Mark the states using Folium &amp; add tooltip for each state with the complete information (state name, confirmed cases, cured cases &amp; death cases. Also highlight the states with maximum &amp; minimum confirmed cases with red &amp; green color."""

covid = pd.read_excel("/content/drive/My Drive/colab/COVID state data.xlsx", header = "infer")

covid

from geopy.geocoders import Nominatim
state_name = input("Enter the state: ");
geolocator = Nominatim(user_agent = 'covid')
location = geolocator.geocode(state_name)
print(location.address)
print((location.latitude, location.longitude))
la , lo = location.latitude, location.longitude;

world_all_cities_tooltip = folium.Map(zoom_start=2)

for _, state in covid.iterrows():
    folium.Marker(
        location=[state_name['la'], state_name['lo']],
         popup=state_name['name'],
         tooltip=state_name['name'],
    ).add_to(world_all_cities_tooltip)
    
world_all_cities_tooltip

"""#### 4: Locate the following locations of the Nagpur city on the map using geopy and folium. Add tooltip, popup info, set specific color and set the suitable icon to the given location. Also mark the area with the circle. 
##### 1) RCOEM 
##### 2) Your home location
##### 3) Two hospitals with + sign 
##### 4) Restaurants 
##### 5) Hotel 
##### 6) Eternity Mall Nagpur 
##### 7) Deekshabhoomi 
##### 8) Temple of Tekdi Ganesh ADD TWO places of your choice.
"""

import csv
fields = ['name','latitude','longitude','hospital','hotel']
rows = [['Ramdeobaba Nagpur','21.1736717','79.060338','no','no'],
        ['Shri Nagar Nagpur','21.1048151','79.1034655','no','no'],
        ['Maxcare Hospital Nagpur','21.1065861','79.0821091','yes','no'],
        ['Kothari Hospital Nagpur','21.1143604','79.0714782','yes','no'],
        ['Radisson Blu Nagpur','21.1060636','79.0697687','no','yes'],
        ['Hotel Orient Prime and Restaurant','21.1559645','79.1151211','no','yes'],
        ['Eternity Mall Nagpur','21.143152049999998','79.08022817813524','no','yes'],
        ['Deekshabhoomi','21.1282013','79.06693','no','no'],
        ['Tekdi Ganesh Nagpur','21.1482027','79.0870216','no','no']]

filename = "places.csv"
with open(filename, 'w') as csvfile:
  csvwriter = csv.writer(csvfile)
  csvwriter.writerow(fields)
  csvwriter.writerows(rows)

places = pd.read_csv('places.csv')
print(places.shape)
places.head(3)

world = folium.Map()
state = places.iloc[1]
folium.Marker(
    location=[state['latitude'], state['longitude']],
).add_to(world)

world

world_all_cities_tooltip = folium.Map(zoom_start=5)

for _, state in places.iterrows():
    folium.Marker(
        location=[state['latitude'], state['longitude']],
         popup=state['name'],
         tooltip=state['name'],
    ).add_to(world_all_cities_tooltip)
    
world_all_cities_tooltip

def select_marker_color(row):
    if row['hotel'] == 'yes':
        return 'blue'
    elif row['hotel'] == 'no' :
        return 'purple'
    return 'pink'

places['colors'] = places.apply(select_marker_color, axis=1)
places.head(3)

world_all_cities_colored = folium.Map(zoom_start=2,
    location=[13.133932434766733, 16.103938729508073]
)

for _, city in places.iterrows():
    folium.Marker(
        location=[city['latitude'], city['longitude']],
        popup=city['name'],
        tooltip= city['name'],
        icon=folium.Icon(color=city['colors'],prefix= 'fa',icon='')
    ).add_to(world_all_cities_colored)
    
world_all_cities_colored

"""##### Task 5: Get Zip Code of given location using GeoPy in Python"""

from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="geoapiExercises")
place = input("Enter the place- ")
location = geolocator.geocode(place)
data = location.raw
loc_data = data['display_name'].split()
print("Full Location")
print(loc_data)
print("Zip code : ",loc_data[-2])

