# -*- coding: utf-8 -*-
"""Seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19VJVin8OtmGHzSrbscv3YS9cAk5NTQaG
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive
drive.mount ('/content/drive')

!ls "/content/drive/MyDrive/colab"

df = pd.read_csv('/content/drive/MyDrive/colab/supermarket_sales - Sheet1.csv', sep = ',', header = "infer")

!pip install seaborn

print(df.shape)

print(df.size)

print(df.dtypes)

df.describe()

df['Date'] = pd.to_datetime(df['Date'])
df.info()

df.info('date')

df

import seaborn as sns

df['hour'] = pd.DatetimeIndex(df['Time']).hour

sns.lineplot(x="hour" , y = "Quantity", data = df)

sns.distplot(df['Unit price'], kde = False
             )

df['year'] = pd.DatetimeIndex(df['Date']).year
df['month'] = pd.DatetimeIndex(df['Date']).month
df['hour'] = pd.DatetimeIndex(df['Time']).hour
df[['month']]

df[['hour']]

Count = sns.relplot(x="Time", y = 'Quantity', col= 'month' , row= 'Branch', kind="line", hue="Gender", style="Gender", data =df)

Count = sns.relplot(x="Time", y = 'Quantity', col= 'month' , row= 'Branch', kind ="line" ,hue="Customer type", data =df)

plt.figure(figsize=(10,6))

for i in range(1,18):
    plt.subplot(18,1,i)

    sns.histplot(data = df, x = df.columns[i])

plt.subplots_adjust(left = 0.1, bottom = 0.1, right = 0.9, top = 4, wspace = 0.4, hspace = 0.5)

sns.countplot(x='Branch',data = df)

sns.countplot(x = 'Payment', data = df)

x = sns.boxplot(x = "Branch",y = "Rating",data = df ,whis = np.inf)

x = sns.boxenplot(x = "Product line",y = "Quantity" ,data = df )

a = sns.swarmplot(x = 'Customer type', y = 'Rating', data =df)

import numpy as np

plt.figure(figsize=(8,4))

rs = np.random.RandomState(10)

ls = rs.normal(size=50)

sns.distplot(ls, color="g")

plt.title("Normal Distribution", fontsize = 20)

plt.show()

plt.figure(figsize=(8,4))

sns.distplot(np.random.binomial(n=100, p=0.5, size=50), hist=True, label='binomial',color='red')

plt.title("Binomial Distribution", fontsize = 20)

plt.show()

plt.figure(figsize=(8,4))

sns.distplot(np.random.poisson(lam=2, size=50))

plt.title("Poisson Distribution", fontsize = 20)

plt.show()

plt.figure(figsize=(10,6))

sns.pairplot(x_vars = ['gross income','Quantity','Unit price','Rating'], y_vars = ['gross income','Quantity','Unit price','Rating'], data = df)

plt.title("Pairplot", fontsize = 20)

correlation = df.corr()
correlation

plt.figure(figsize=(10,6))

sns.heatmap(data = correlation,annot=annot)
annot = True
plt.title("Correlation of all the columns", fontsize = 20)

plt.figure(figsize=(10,6))

sns.countplot(x = 'Payment', hue = "Branch", data = df)

plt.title("Payment Channel by Branch", fontsize = 20)

plt.figure(figsize=(10,6))

sns.countplot(x = "Gender", data = df)

plt.title("Gender_count", fontsize = 20)

plt.figure(figsize=(10,6))
sns.countplot(y = "Product line", hue = "Payment", data = df)

plt.title("Payment per Product line", fontsize = 20)

